// components/MovieList.vue
<template>
  <div class="box bg-[#211c1e] h-full relative">
    <div
      class="p-5 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-4"
    >
      <MovieCard v-for="(movie, index) in movies" :key="movie.id" :movie="movie" :index="index" />
    </div>
    <button  v-show="showScrollTop" @click="scrollToTop" class="scroll-to-top  ">↑</button>
  </div>
</template>

<script setup lang="ts">
import MovieCard from "~/components/MovieStyle/MovieCard.vue";
import type { MovieType } from "~/types/movie";
import type { PropType } from "vue";

const showScrollTop = ref<boolean>(false);
const props = defineProps({
  movies: {
    type: Array as PropType<MovieType[]>,
    required: true,
  }
});
const handleScroll = () => {
  showScrollTop.value = window.scrollY > 200;
};

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: 'smooth' });
};
onMounted(async () => {
    window.addEventListener('scroll', handleScroll);
});

</script>

<style lang="scss">
@import "/assets/css/MovieList.scss";
</style>

// components/MovieList.tsx
'use client'

import { useEffect, useState } from 'react'
import { MovieType } from '@/types/movie'
import MovieCard from './MovieStyle/MovieCard'

export default function MovieList({ movies }: { movies: MovieType[] }) {
  const [showScrollTop, setShowScrollTop] = useState(false)

  useEffect(() => {
    const handleScroll = () => setShowScrollTop(window.scrollY > 200)
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  return (
    <div className="box bg-[#211c1e] h-full relative">
      <div className="p-5 grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
        {movies.map((movie, index) => (
          <MovieCard key={movie.id} movie={movie} priority={index < 4} />
        ))}
      </div>
      {showScrollTop && (
        <button
          className="scroll-to-top"
          onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
        >
          ↑
        </button>
      )}
    </div>
  )
}
